export enum MdTokenType {
    Heading = 'heading',
    Paragraph = 'paragraph',
    List = 'list',
    ListItem = 'list_item',
    Blockquote = 'blockquote',
    Code = 'code',
    CodeSpan = 'codespan',
    Table = 'table',
    Html = 'html',
    Hr = 'hr',
    Image = 'image',
    Link = 'link',
    Strong = 'strong',
    Em = 'em',
    TableHeader = 'table_header',
    TableCell = 'table_cell',
    Raw = 'raw',
    Text = 'text',
}
